import type { CSSEffect } from "@/data/effects"

/**
 * Convert a snippet of HTML into a framework-neutral JSX-ish string:
 * self-closing void tags, className instead of class, escaped braces.
 */
function htmlToJsx(html: string): string {
  let out = html
  out = out.replace(/\bclass=/g, "className=")
  const voids = ["input", "br", "img", "hr", "meta", "link", "source"]
  out = out.replace(
    new RegExp(`<(${voids.join("|")})\\b([^>]*?)(?<!\\/)>`, "g"),
    "<$1$2 />"
  )
  out = out.replace(/(?<!\\)\{/g, "&#123;").replace(/(?<!\\)\}/g, "&#125;")
  return out.trim()
}

/** Indent each line of a string by `indent`. */
function indent(src: string, indent: string): string {
  return src
    .split("\n")
    .map((l) => (l.length ? indent + l : l))
    .join("\n")
}

/**
 * Prefix every selector in the CSS with the scope class so styles don't leak
 * globally. Renames @keyframes + animation references to avoid collisions.
 */
function scopeCss(css: string, scope: string): string {
  let out = css
  out = out.replace(/(@keyframes\s+)([A-Za-z0-9_-]+)/g, (_, at, name) => `${at}${scope}-${name}`)
  out = out.replace(/(animation[^:]*:\s*)([A-Za-z0-9_-]+)/g, (_, prefix, name) => {
    if (/^(ease|linear|infinite|forwards|backwards|both|in|out|alternate|reverse|running|paused)$/.test(name)) {
      return _
    }
    return `${prefix}${scope}-${name}`
  })
  const segments = out.split(/(@keyframes[^{}]*\{[^}]*\})/g)
  return segments
    .map((seg, i) => {
      if (i % 2 === 1) return seg
      return seg.replace(
        /^([^@{}][^{}]*)\{/gm,
        (full, selectorPart: string) => {
          const scoped = selectorPart
            .split(",")
            .map((s: string) => {
              const trimmed = s.trim()
              if (!trimmed) return s
              return ` .${scope} ${trimmed}`.replace(/\s+/g, " ")
            })
            .join(", ")
          return `${scoped} {`
        }
      )
    })
    .join("")
}

/** Derive a PascalCase component name from an effect id. */
function compName(effect: CSSEffect): string {
  return (
    "Fx" +
    effect.id
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("")
  )
}

/** A safe scope class derived from the effect id. */
function scopeClass(effect: CSSEffect): string {
  return effect.id.replace(/[^a-zA-Z0-9-]/g, "")
}

export type Framework = "react" | "vue" | "svelte"

/** Build a ready-to-paste React component string from an effect. */
export function toReactComponent(effect: CSSEffect): string {
  const name = compName(effect)
  const scope = scopeClass(effect)
  const scopedCss = scopeCss(effect.css, scope)
  const jsx = htmlToJsx(effect.html)
  const wrappedJsx = `<div className="${scope}">\n${indent(jsx, "  ")}\n</div>`

  return `// ${effect.name} — generated by CSSFX
// Paste into any React project. Self-contained (styles are scoped).
export function ${name}() {
  return (
    <>
      <style>{\`${"\n"}${scopedCss}${"\n"}\`}</style>
${indent(wrappedJsx, "      ")}
    </>
  )
}
`
}

/** Build a ready-to-paste Vue 3 SFC (single-file component) string. */
export function toVueComponent(effect: CSSEffect): string {
  const name = compName(effect)
  const scope = scopeClass(effect)
  const scopedCss = scopeCss(effect.css, scope)
  // Vue templates use plain `class` (not className), so use the raw HTML.
  const wrappedTemplate = `<div class="${scope}">\n${indent(effect.html.trim(), "    ")}\n  </div>`

  return `<!-- ${effect.name} — generated by CSSFX -->
<!-- Paste as a Vue 3 SFC (e.g. ${name}.vue). Self-contained (styles are scoped). -->
<script setup lang="ts">
// ${name} — pure CSS effect, no logic needed.
</script>

<template>
${indent(wrappedTemplate, "  ")}
</template>

<style scoped>
${indent(scopedCss, "")}
</style>
`
}

/** Build a ready-to-paste Svelte component string. */
export function toSvelteComponent(effect: CSSEffect): string {
  const name = compName(effect)
  const scope = scopeClass(effect)
  const scopedCss = scopeCss(effect.css, scope)
  // Svelte templates use plain `class` (not className), so use the raw HTML.
  const wrappedMarkup = `<div class="${scope}">\n${indent(effect.html.trim(), "  ")}\n</div>`

  return `<!-- ${effect.name} — generated by CSSFX -->
<!-- Paste as a Svelte component (e.g. ${name}.svelte). Self-contained (styles are scoped). -->
<script lang="ts">
// ${name} — pure CSS effect, no logic needed.
</script>

${wrappedMarkup}

<style>
${indent(scopedCss, "")}
</style>
`
}

/** Dispatch to the right framework transform. */
export function toComponent(effect: CSSEffect, fw: Framework): string {
  if (fw === "vue") return toVueComponent(effect)
  if (fw === "svelte") return toSvelteComponent(effect)
  return toReactComponent(effect)
}

/** Suggested download filename for a given framework. */
export function componentFilename(effect: CSSEffect, fw: Framework): string {
  const base = compName(effect)
  const ext = fw === "react" ? "jsx" : fw === "vue" ? "vue" : "svelte"
  return `${base}.${ext}`
}
